### ISSUE TITLE
Text in content can't be Bold, Italic, Underline, Marked, and Hidden

### ISSUE THREAD

**Issue by kevfrederico** [imfery/INDONADS-WIKI-FE#20]
Task summary :
Please make a feature for text in content works: bold, italic, underline, maker, text spoiler 

Evidence :
![image](https://github.com/user-attachments/assets/18ecc73b-017d-4f8c-88ee-fa0525d7697a)

**Comment by imfery** [comment]
resolved https://github.com/imfery/INDONADS-WIKI-BE/commit/ba33cd690a70493f9a78d86d7deb83af9c656633
